name: Testing workflow

on: [push]


jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: "Install style checker"
        run: pip3 install black
      - name: "Run style check"
        run: black --check .
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: "Install test dependencies"
        run: pip3 install pytest numpy matplotlib
      - name: "Install coverage"
        run: pip3 install coverage
      - name: "Run tests using coverage"
        run: coverage run -m pytest
      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: coverage_file
          path: .coverage
          retention-days: 1
          if-no-files-found: error
  coverage_report:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: "Install coverage"
        run: pip3 install coverage
      - uses: actions/download-artifact@v3
        with:
          name: coverage_file
      - name: "Create coverage report"
        run: coverage report
      - name: "Create coverage.xml"
        run: coverage xml
      - name: "Upload xml file"
        uses: actions/upload-artifact@v3    
        with:
          name: coverage.xml
          path: coverage.xml
          retention-days: 14
          if-no-files-found: error
    
